# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm8475-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter eqs,$(TARGET_DEVICE)),)

endif
